name: ShellCheck

on:
  push:
    branches: [ main ]
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'
  workflow_dispatch:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck
      
      - name: Find shell scripts
        id: find_scripts
        run: |
          echo "SCRIPTS=$(find . -type f -name "*.sh" | tr '\n' ' ')" >> $GITHUB_ENV
      
      - name: Run ShellCheck (informational)
        run: |
          echo "Running ShellCheck in informational mode..."
          shellcheck --version
          shellcheck --shell=bash --format=gcc --enable=all ${{ env.SCRIPTS }} || true
      
      - name: Run ShellCheck (required)
        run: |
          echo "Running ShellCheck with required checks..."
          # More lenient mode - only fails on errors, not warnings
          shellcheck --shell=bash --format=gcc --severity=error ${{ env.SCRIPTS }}
          
          # Specific directories that should pass stricter checks
          if [ -d "./core" ]; then
            echo "Running stricter checks on core files..."
            shellcheck --shell=bash --format=gcc --severity=warning ./core/*.sh
          fi
